version: '3'
services:
        db:
                image: postgres:14.1-alpine
                container_name: postgres
                ports:
                        - "5432:5432"
                volumes:
                        - ./pg_data:/var/lib/postgresql/data/pgdata
                environment:
                        POSTGRES_USER: postgres
                        POSTGRES_PASSWORD: 1006
                        POSTGRES_DB: Docker_compose_test
                        PGDATA: /var/lib/postgresql/data/pgdata
                restart: always
        app:
                build: ./dockerfile
                image: nodejs/npm:v1
                container_name: nodejs
                expose:
                        - "3000"
                restart: always
                
        nginx:
                image: nginx:1.21.5-alpine
                container_name: nginx
                ports:
                        - "80:80"
                volumes: 
                        - ./default.conf:/etc/nginx/conf.d/default.conf
                depends_on:
                        - app

